version: '3'
services:
  pg:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=DEV-_^+3{,ewt{_bgA@X!;(p,;na-}4x9h*Y
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim_dev
    ports:
      - "5432:5432"
  
  mailer:  
    image: tophfr/mailcatcher
    ports:
      - "1080:80"
    networks:
      - default

volumes:
  pg-data: {}
